### ISSUE TITLE
Running on Python 3 in Windows results in failure to read CSV

### ISSUE THREAD

**Issue by kcollins-ene** [crooke/ignition-translation-converter#2]
When you run the tool with Python 3 in Windows, it fails with the following error:

    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 47: character maps to <undefined>

This seems to be due to the default encoding being different on Windows (`cp1252`) which you can see by running `locale.getpreferredencoding(False)` on Windows:

    Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import locale
    >>> locale.getpreferredencoding(False)
    'cp1252'
    >>>

... then it is on macOS or Linux:

    Python 3.6.5 (default, Mar 30 2018, 06:41:53)
    [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import locale
    >>> locale.getpreferredencoding(False)
    'UTF-8'

Recommend explicitly setting the encoding to 'UTF-8' to avoid this..  Pull request coming soon. 😄

**Comment by crooke** [comment]
Thanks for the fix, @kcollins-ene!
